import { Router } from 'express';
import { walletRouter } from './wallet.js';
import { installationsRouter } from './installations.js';
import { proofsRouter } from './proofs.js';
import { batchesRouter } from './batches.js';
import { nftsRouter } from './nfts.js';
import { daoRouter } from './dao.js';
import { treasuryRouter } from './treasury.js';
import { marketplaceRouter } from './marketplace.js';
import { impactRouter } from './impact.js';
import { adminRouter } from './admin.js';
import { notificationsRouter } from './notifications.js';
import { yieldRouter } from './yield.js';
import { swapRouter } from './swap.js';
import { delegationRouter } from './delegation.js';
import { vaultRouter } from './vault.js';
import { agentsRouter } from './agents.js';
import { chartsRouter } from './charts.js';
import { crosschainRouter } from './crosschain.js';
import { scoresRouter } from './scores.js';
import { rewardsRouter } from './rewards.js';
import { economyRouter } from './economy.js';

export const router = Router();

router.use('/scores', scoresRouter);
router.use('/rewards', rewardsRouter);
router.use('/wallet', walletRouter);
router.use('/installations', installationsRouter);
router.use('/proofs', proofsRouter);
router.use('/batches', batchesRouter);
router.use('/nfts', nftsRouter);
router.use('/dao', daoRouter);
router.use('/treasury', treasuryRouter);
router.use('/marketplace', marketplaceRouter);
router.use('/impact', impactRouter);
router.use('/admin', adminRouter);
router.use('/notifications', notificationsRouter);
router.use('/yield', yieldRouter);
router.use('/swap', swapRouter);
router.use('/delegation', delegationRouter);
router.use('/vault', vaultRouter);
router.use('/agents', agentsRouter);
router.use('/charts', chartsRouter);
router.use('/crosschain', crosschainRouter);
router.use('/economy', economyRouter);
